// Generated by CoffeeScript 2.7.0
import {
  minifyHtml
} from "@cedx/esbuild-plugins";

import esbuild from "esbuild";

await esbuild.build({
  ...theRestOfYourConfig,
  plugins: [minifyHtml()]
});
